<a href="https://colab.research.google.com/github/Olmedann/Portafolio/blob/main/Matriz_de_transicion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -q https://github.com/ivanGarciaBernal/markov-chain-stimation/raw/main/Datos/datos.zip
!unzip datos.zip

Archive:  datos.zip
  inflating: gen14.xlsx              
  inflating: gen15.xlsx              
  inflating: gen1601.xlsx            
  inflating: gen1602.xlsx            
  inflating: gen17.xlsx              
  inflating: gen18.xlsx              
  inflating: gen19.xlsx              
  inflating: gen20.xlsx              
  inflating: gen21.xlsx              
  inflating: gen22.xlsx              


In [ ]:
import pandas as pd
import numpy as np

gen14 = pd.read_excel("gen14.xlsx")
gen15 = pd.read_excel("gen15.xlsx")
gen1601 = pd.read_excel("gen1601.xlsx")
gen1602 = pd.read_excel("gen1602.xlsx")
gen16 = gen1601 + gen1602
gen17 = pd.read_excel("gen17.xlsx")
gen18 = pd.read_excel("gen18.xlsx")
gen19 = pd.read_excel("gen19.xlsx")
gen20 = pd.read_excel("gen20.xlsx")
gen21 = pd.read_excel("gen21.xlsx")
gen22 = pd.read_excel("gen22.xlsx")

archivos = [gen14,
            gen15,
            gen16,
            gen17,
            gen18,
            gen19,
            gen20,
            gen21,
            gen22]

def obtener_estados(tabla):
    matriz = np.zeros((12,12))
    #ponemos 1 a los estados absorbentes
    matriz[11,11] = 1
    matriz[10,10] = 1
    # semestres
    diagonal = [tabla[columna][columna - 1] for columna in range(2,11)]
    #llenamos los datos en la matriz
    for i in range(1,10):
        matriz[i-1][i] = diagonal[i-1]
    #alumnos rezagados
    rezagados = [p-a for p,a in zip(tabla["Poblacion"][1:11],diagonal)]
    #llenamos los datos en la matriz
    for i,x in enumerate(rezagados):
        matriz[i][i] = x
    #alumnos desertores
    desertores = [tabla["Poblacion"][i-1] - tabla["Poblacion"][i] for i in range(1,10)]
    #escribimos
    for i,x in enumerate(desertores):
        matriz[i][11] = x
    #Egresados
    numero_egresados = tabla["Egresados"].iat[-1]
    matriz[9][10] = numero_egresados
    matriz[9][9] = numero_egresados - tabla["Egresados"].iat[9]
    matriz[9][11] = tabla["Poblacion"][8] - tabla["Poblacion"][9]
    return np.nan_to_num(matriz)

def obtener_matriz(tabla):
    for i in range(12):
        if sum(tabla[i]) > 0:
            tabla[i] = 1/(sum(tabla[i])) * tabla[i]
    return np.nan_to_num(tabla)

def matriz_transicion(tabla):
    return obtener_matriz(obtener_estados(tabla))

# lista que contiene la matriz de conteo de cada generacion
E = list(map(obtener_estados,archivos))



In [ ]:
## 14 15 16
matriz_14_15_16 = obtener_matriz(sum(E[:3]))
A = pd.DataFrame(matriz_14_15_16)
A.to_excel("matriz_14_a_16.xlsx")
A

0         1         2         3         4         5         6         7   \
0   0.0  0.597315  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.0  0.044944  0.730337  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.0  0.000000  0.057971  0.811594  0.000000  0.000000  0.000000  0.000000   
3   0.0  0.000000  0.000000  0.150000  0.733333  0.000000  0.000000  0.000000   
4   0.0  0.000000  0.000000  0.000000  0.169811  0.735849  0.000000  0.000000   
5   0.0  0.000000  0.000000  0.000000  0.000000  0.187500  0.750000  0.000000   
6   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.155556  0.733333   
7   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.150000   
8   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          8         9         10        11  
0   0.000000  0.000000  0.000000  0.402685  
1   0.000000  0.000000  0.000000  0.224719  
2   0.000000  0.000000  0.000000  0.130435  
3   0.000000  0.000000  0.000000  0.116667  
4   0.000000  0.000000  0.000000  0.094340  
5   0.000000  0.000000  0.000000  0.062500  
6   0.000000  0.000000  0.000000  0.111111  
7   0.800000  0.000000  0.000000  0.050000  
8   0.263158  0.736842  0.000000  0.000000  
9   0.000000  0.333333  0.666667  0.000000  
10  0.000000  0.000000  1.000000  0.000000  
11  0.000000  0.000000  0.000000  1.000000

In [ ]:
matriz_17_18_19 = obtener_matriz(sum(E[3:6]))
B = pd.DataFrame(matriz_17_18_19)
B.to_excel("matriz_17_a_19.xlsx")
B

0         1         2         3         4         5         6     7   \
0   0.0  0.696429  0.000000  0.000000  0.000000  0.000000  0.000000  0.00   
1   0.0  0.042735  0.863248  0.000000  0.000000  0.000000  0.000000  0.00   
2   0.0  0.000000  0.094340  0.830189  0.000000  0.000000  0.000000  0.00   
3   0.0  0.000000  0.000000  0.316327  0.632653  0.000000  0.000000  0.00   
4   0.0  0.000000  0.000000  0.000000  0.344086  0.569892  0.000000  0.00   
5   0.0  0.000000  0.000000  0.000000  0.000000  0.400000  0.541176  0.00   
6   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.425000  0.55   
7   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.50   
8   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.00   
9   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.00   
10  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.00   
11  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.00   

          8         9         10        11  
0   0.000000  0.000000  0.000000  0.303571  
1   0.000000  0.000000  0.000000  0.094017  
2   0.000000  0.000000  0.000000  0.075472  
3   0.000000  0.000000  0.000000  0.051020  
4   0.000000  0.000000  0.000000  0.086022  
5   0.000000  0.000000  0.000000  0.058824  
6   0.000000  0.000000  0.000000  0.025000  
7   0.474359  0.000000  0.000000  0.025641  
8   0.527273  0.345455  0.000000  0.127273  
9   0.000000  0.171429  0.628571  0.200000  
10  0.000000  0.000000  1.000000  0.000000  
11  0.000000  0.000000  0.000000  1.000000

In [ ]:
matriz_20_21 = obtener_matriz(sum(E[6:8]))
C = pd.DataFrame(matriz_20_21)
for i in range(6,10):
  C[i][i] = 1
C.to_excel("matriz_20_21.xlsx")


In [ ]:
matriz_14_hasta_19 = obtener_matriz(sum(E[:6]))
D = pd.DataFrame(matriz_14_hasta_19)
D.to_excel("matriz_14_a_19.xlsx")


In [ ]:
!pip install PyDTMC

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.5/76.5 kB 1.2 MB/s eta 0:00:00


In [ ]:
import pydtmc as mc

In [ ]:
nombres = ['1','2','3','4','5','6','7','8','9','10','E','D']

In [ ]:
P_14_15_16 = mc.MarkovChain(matriz_14_15_16,nombres)
print(P_14_15_16),P_14_15_16.absorption_probabilities(),P_14_15_16.mean_absorption_times()


DISCRETE-TIME MARKOV CHAIN
 SIZE:           12
 RANK:           11
 CLASSES:        12
  > RECURRENT:   2
  > TRANSIENT:   10
 ERGODIC:        NO
  > APERIODIC:   YES
  > IRREDUCIBLE: NO
 ABSORBING:      YES
 MONOTONE:       NO
 REGULAR:        NO
 REVERSIBLE:     NO
 SYMMETRIC:      NO



(None,
 array([[0.22704219, 0.38010434, 0.49705952, 0.57694409, 0.66873065,
         0.75446535, 0.81733746, 0.94117647, 1.        , 1.        ],
        [0.77295781, 0.61989566, 0.50294048, 0.42305591, 0.33126935,
         0.24553465, 0.18266254, 0.05882353, 0.        , 0.        ]]),
 array([4.61405775, 6.05050118, 6.54296308, 6.36236786, 6.01092638,
        5.42258361, 4.54113224, 3.86554622, 2.85714286, 1.5       ]))

In [ ]:
P_17_18_19 = mc.MarkovChain(matriz_17_18_19,nombres)
print(P_17_18_19),P_17_18_19.absorption_probabilities()


DISCRETE-TIME MARKOV CHAIN
 SIZE:           12
 RANK:           11
 CLASSES:        12
  > RECURRENT:   2
  > TRANSIENT:   10
 ERGODIC:        NO
  > APERIODIC:   YES
  > IRREDUCIBLE: NO
 ABSORBING:      YES
 MONOTONE:       NO
 REGULAR:        NO
 REVERSIBLE:     NO
 SYMMETRIC:      NO



(None,
 array([[0.2100288 , 0.30157981, 0.33442514, 0.36482742, 0.39424899,
         0.45375827, 0.50307982, 0.52594709, 0.55437666, 0.75862069],
        [0.7899712 , 0.69842019, 0.66557486, 0.63517258, 0.60575101,
         0.54624173, 0.49692018, 0.47405291, 0.44562334, 0.24137931]]))

In [ ]:
P_20_21 = mc.MarkovChain(matriz_20_21,nombres)
print(P_20_21),P_20_21.absorption_probabilities(), P_20_21.mean_absorption_times()


DISCRETE-TIME MARKOV CHAIN
 SIZE:           12
 RANK:           12
 CLASSES:        12
  > RECURRENT:   6
  > TRANSIENT:   6
 ERGODIC:        NO
  > APERIODIC:   YES
  > IRREDUCIBLE: NO
 ABSORBING:      YES
 MONOTONE:       NO
 REGULAR:        NO
 REVERSIBLE:     NO
 SYMMETRIC:      NO



(None,
 array([[0.26931194, 0.46287989, 0.58911986, 0.66873065, 0.70588235,
         0.8       ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.73068806, 0.53712011, 0.41088014, 0.33126935, 0.29411765,
         0.2       ]]),
 array([3.62280778, 4.49232588, 4.24023294, 3.38080495, 2.23529412,
        1.2       ]))

In [ ]:
P_14_hasta_19 = mc.MarkovChain(matriz_14_hasta_19,nombres)
print(P_14_hasta_19),P_14_hasta_19.absorption_probabilities(),P_14_hasta_19.mean_absorption_times()


DISCRETE-TIME MARKOV CHAIN
 SIZE:           12
 RANK:           11
 CLASSES:        12
  > RECURRENT:   2
  > TRANSIENT:   10
 ERGODIC:        NO
  > APERIODIC:   YES
  > IRREDUCIBLE: NO
 ABSORBING:      YES
 MONOTONE:       NO
 REGULAR:        NO
 REVERSIBLE:     NO
 SYMMETRIC:      NO



(None,
 array([[0.2371911 , 0.36499795, 0.43316022, 0.48429719, 0.53912328,
         0.61530375, 0.67533338, 0.73672732, 0.77943615, 0.89552239],
        [0.7628089 , 0.63500205, 0.56683978, 0.51570281, 0.46087672,
         0.38469625, 0.32466662, 0.26327268, 0.22056385, 0.10447761]]),
 array([6.04277748, 7.76000224, 7.96819543, 7.69360739, 7.07401578,
        6.48664844, 5.49754097, 4.3739408 , 2.91735766, 1.37313433]))

In [ ]:
def imprime_excel(matriz,nombre,col = list(range(1,11)) ):
  pd.DataFrame(matriz.absorption_probabilities(),columns = col).to_excel("prob abs" + nombre)
  pd.DataFrame(matriz.mean_absorption_times()).to_excel("mean absorbtion" + nombre)

In [ ]:
imprime_excel(P_14_15_16,"P 14 16.xlsx")
imprime_excel(P_17_18_19,"P 17 19.xlsx")
imprime_excel(P_20_21,"P 20 21.xlsx",col = list(range(1,7)))
imprime_excel(P_14_hasta_19,"P 14 19.xlsx")

In [ ]:
P_20_21.absorbing_states

['7', '8', '9', '10', 'E', 'D']

Calculo de matrices sin considerar la pandemia

In [ ]:
def no_pandemia(gen,semestre,final = None):
  m = obtener_estados(gen)
  m[semestre - 1:final,:] = 0
  return m
npd15 = no_pandemia(gen15,10)
npd16 = no_pandemia(gen16,8)
npd17 = no_pandemia(gen17,6,10)
npd18 = no_pandemia(gen18,4,8)
npd19 = no_pandemia(gen19,2,6)

nopd = sum([obtener_estados(gen14),
            npd15,
            npd16,
            npd17,
            npd18,
            npd19])
pd.DataFrame(obtener_matriz(nopd)).to_excel("matriz no pandemia.xlsx")
P = mc.MarkovChain(obtener_matriz(nopd),nombres)
pd.DataFrame(P.absorption_probabilities(),columns=list(range(1,11))).to_excel("abs prob no pandemia.xlsx")
pd.DataFrame(P.mean_absorption_times()).to_excel("mean time absorption.xlsx")
